site_name: ONB Modding
site_url: https://alrysc.github.io/onb_docs

theme:
  name: material
  palette:
    - scheme: slate
      toggle:
        icon: material/weather-sunny
        name: Dark mode
      primary: green

    - scheme: default
      toggle:
        icon: material/weather-night
        name: Light mode
      primary: blue

  features:
    - navigation.instant
    - navigation.instant.progress
    - navigation.tabs
    - navigation.expand
    - content.code.copy
    - content.code.select

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - admonition
  - pymdownx.details

nav:
  - Home:
      - Introduction: index.md
      - Changelog: changelog.md
  - Lua Primer:
      - Overview: lua/index.md
      - Comments: lua/comments.md
      - Variables:
          - Overview: lua/variables/index.md
          - Numbers: lua/variables/numbers.md
          - Strings: lua/variables/strings.md
          - Booleans: lua/variables/booleans.md
          - Functions: lua/variables/functions.md
          - Tables: lua/variables/tables.md
      - Boolean Expressions: lua/boolean_expressions.md
      - Comparisons: lua/comparisons.md
      - Control Structures: lua/control_structures.md
      - Scope: lua/scope.md
      - Tables As Objects: lua/objects.md
      - Useful Functions: lua/useful_functions.md
  - Engine Objects:
      - Introduction: onb_overview/index.md
      - Entities:
          - Entity: onb_overview/entities/index.md
          - Artifact: onb_overview/entities/artifact.md
          - Spell: onb_overview/entities/spell.md
          - Obstacle: onb_overview/entities/obstacle.md
          - Character: onb_overview/entities/character.md
          - Player: onb_overview/entities/player.md
      - Enums:
          - Overview: onb_overview/enums/index.md
          - Element: onb_overview/enums/element.md
          - Direction: onb_overview/enums/direction.md
          - Team: onb_overview/enums/team.md
          - Input: onb_overview/enums/input.md
          - Rank: onb_overview/enums/rank.md
          - Shadow: onb_overview/enums/shadow.md
          - ColorMode: onb_overview/enums/colormode.md
          - Playback: onb_overview/enums/playback.md
          - AudioPriority: onb_overview/enums/audiopriority.md
          - AudioType: onb_overview/enums/audiotype.md
          - CardClass: onb_overview/enums/cardclass.md
          - Blocks: onb_overview/enums/blocks.md
          - EntityStatus: onb_overview/enums/entitystatus.md
